repos:
  - repo: local
    hooks:
      - id: lint-package
        name: Lint Package
        entry: ./lint_package.sh
        language: system
        pass_filenames: true
        files: \.py$
        stages: [commit]
      - id: lint-docs
        name: Lint Documentation
        entry: ./lint_docs.sh
        language: system
        pass_filenames: true
        files: ^docs/.*\.(py|qmd)$
        stages: [commit]